[project]
name = "basicMLTemplate"
description = "A project that does ML stuff"
authors = ["DawnMagnet<axccjqh@qq.com>"]
channels = ["conda-forge", "pytorch"]
platforms = ["win-64", "linux-64"]

[dependencies]
python = "3.12.*"
pytorch = { version = "==2.3", channel = "pytorch" }
torchvision = { version = "*", channel = "pytorch" }
torchaudio = { version = "*", channel = "pytorch" }

ipykernel = "*"
seaborn = "*"
timm = "*"
setuptools = "*"
pip = "*"
einops = "*"

[feature.cuda118]
platforms = ["win-64", "linux-64"]
channels = ["nvidia", { channel = "pytorch", priority = -1 }]
system-requirements = { cuda = "11.8" }

[feature.cuda118.dependencies]
pytorch-cuda = { version = "11.8.*", channel = "pytorch" }
cuda-toolkit = { version = "11.8.*", channel = "nvidia" }

[feature.cuda121]
platforms = ["win-64", "linux-64"]
channels = ["nvidia", { channel = "pytorch", priority = -1 }]
system-requirements = { cuda = "12.1" }

[feature.cuda121.dependencies]
pytorch-cuda = { version = "12.1.*", channel = "pytorch" }
# cuda-toolkit = { version = "12.1.*", channel = "nvidia" }


[feature.cpu]
platforms = ["win-64", "linux-64"]

[environments]
# cuda = ["cuda118"]
# cuda11 = ["cuda118"]
# cuda12 = ["cuda121"]
# cpu = ["cpu"]
default = ["cuda121"]

[pypi-options]
no-build-isolation = ["selective-scan-cuda", "ultralytics"]
[pypi-dependencies]
thop = ">=0.1.1.post2209072238, <0.2"
# current path as package
selective-scan-cuda = {path = "selective_scan"}

ultralytics = { path = "." }